apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payments
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
spec:
  project: default
  source:
    repoURL: https://github.com/shreekarki/test-argo-sync.git
    targetRevision: main
    path: services/payments
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  # NOTE: no syncPolicy.automated — auto-sync OFF
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: billing
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
spec:
  project: default
  source:
    repoURL: https://github.com/shreekarki/test-argo-sync.git
    targetRevision: main
    path: services/billing
  destination:
    server: https://kubernetes.default.svc
    namespace: default
